// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Send A Key-Value
type KeyValueRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValueRequest) Reset()         { *m = KeyValueRequest{} }
func (m *KeyValueRequest) String() string { return proto.CompactTextString(m) }
func (*KeyValueRequest) ProtoMessage()    {}
func (*KeyValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1221e02b2e905187, []int{0}
}
func (m *KeyValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValueRequest.Unmarshal(m, b)
}
func (m *KeyValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValueRequest.Marshal(b, m, deterministic)
}
func (dst *KeyValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValueRequest.Merge(dst, src)
}
func (m *KeyValueRequest) XXX_Size() int {
	return xxx_messageInfo_KeyValueRequest.Size(m)
}
func (m *KeyValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValueRequest proto.InternalMessageInfo

func (m *KeyValueRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValueRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Send a Key
type KeyRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyRequest) Reset()         { *m = KeyRequest{} }
func (m *KeyRequest) String() string { return proto.CompactTextString(m) }
func (*KeyRequest) ProtoMessage()    {}
func (*KeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1221e02b2e905187, []int{1}
}
func (m *KeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyRequest.Unmarshal(m, b)
}
func (m *KeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyRequest.Marshal(b, m, deterministic)
}
func (dst *KeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyRequest.Merge(dst, src)
}
func (m *KeyRequest) XXX_Size() int {
	return xxx_messageInfo_KeyRequest.Size(m)
}
func (m *KeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeyRequest proto.InternalMessageInfo

func (m *KeyRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// Return a Record
type Record struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1221e02b2e905187, []int{2}
}
func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (dst *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(dst, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Record) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Return a Empty Deleted Record
type DeletedRecord struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletedRecord) Reset()         { *m = DeletedRecord{} }
func (m *DeletedRecord) String() string { return proto.CompactTextString(m) }
func (*DeletedRecord) ProtoMessage()    {}
func (*DeletedRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1221e02b2e905187, []int{3}
}
func (m *DeletedRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletedRecord.Unmarshal(m, b)
}
func (m *DeletedRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletedRecord.Marshal(b, m, deterministic)
}
func (dst *DeletedRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletedRecord.Merge(dst, src)
}
func (m *DeletedRecord) XXX_Size() int {
	return xxx_messageInfo_DeletedRecord.Size(m)
}
func (m *DeletedRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletedRecord.DiscardUnknown(m)
}

var xxx_messageInfo_DeletedRecord proto.InternalMessageInfo

func init() {
	proto.RegisterType((*KeyValueRequest)(nil), "api.KeyValueRequest")
	proto.RegisterType((*KeyRequest)(nil), "api.KeyRequest")
	proto.RegisterType((*Record)(nil), "api.Record")
	proto.RegisterType((*DeletedRecord)(nil), "api.DeletedRecord")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StoreClient is the client API for Store service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoreClient interface {
	// Sends a greeting
	SetValue(ctx context.Context, in *KeyValueRequest, opts ...grpc.CallOption) (*Record, error)
	GetValue(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*Record, error)
	DeleteValue(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*DeletedRecord, error)
}

type storeClient struct {
	cc *grpc.ClientConn
}

func NewStoreClient(cc *grpc.ClientConn) StoreClient {
	return &storeClient{cc}
}

func (c *storeClient) SetValue(ctx context.Context, in *KeyValueRequest, opts ...grpc.CallOption) (*Record, error) {
	out := new(Record)
	err := c.cc.Invoke(ctx, "/api.Store/SetValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) GetValue(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*Record, error) {
	out := new(Record)
	err := c.cc.Invoke(ctx, "/api.Store/GetValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) DeleteValue(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*DeletedRecord, error) {
	out := new(DeletedRecord)
	err := c.cc.Invoke(ctx, "/api.Store/DeleteValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServer is the server API for Store service.
type StoreServer interface {
	// Sends a greeting
	SetValue(context.Context, *KeyValueRequest) (*Record, error)
	GetValue(context.Context, *KeyRequest) (*Record, error)
	DeleteValue(context.Context, *KeyRequest) (*DeletedRecord, error)
}

func RegisterStoreServer(s *grpc.Server, srv StoreServer) {
	s.RegisterService(&_Store_serviceDesc, srv)
}

func _Store_SetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).SetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Store/SetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).SetValue(ctx, req.(*KeyValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Store/GetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).GetValue(ctx, req.(*KeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_DeleteValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).DeleteValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Store/DeleteValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).DeleteValue(ctx, req.(*KeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Store_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Store",
	HandlerType: (*StoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetValue",
			Handler:    _Store_SetValue_Handler,
		},
		{
			MethodName: "GetValue",
			Handler:    _Store_GetValue_Handler,
		},
		{
			MethodName: "DeleteValue",
			Handler:    _Store_DeleteValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_1221e02b2e905187) }

var fileDescriptor_api_1221e02b2e905187 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0xb2, 0xe4, 0xe2, 0xf7, 0x4e,
	0xad, 0x0c, 0x4b, 0xcc, 0x29, 0x4d, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe0,
	0x62, 0xce, 0x4e, 0xad, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x85, 0x44, 0xb8,
	0x58, 0xcb, 0x40, 0x2a, 0x24, 0x98, 0xc0, 0x62, 0x10, 0x8e, 0x92, 0x1c, 0x17, 0x97, 0x77, 0x6a,
	0x25, 0x4e, 0x5d, 0x4a, 0x06, 0x5c, 0x6c, 0x41, 0xa9, 0xc9, 0xf9, 0x45, 0x29, 0x44, 0x9b, 0xc8,
	0xcf, 0xc5, 0xeb, 0x92, 0x9a, 0x93, 0x5a, 0x92, 0x9a, 0x02, 0xd1, 0x68, 0x34, 0x8b, 0x91, 0x8b,
	0x35, 0xb8, 0x24, 0xbf, 0x28, 0x55, 0x48, 0x9f, 0x8b, 0x23, 0x38, 0xb5, 0x04, 0xec, 0x4e, 0x21,
	0x11, 0x3d, 0x90, 0x27, 0xd0, 0x9c, 0x2d, 0xc5, 0x0d, 0x16, 0x85, 0x68, 0x54, 0x62, 0x10, 0xd2,
	0xe2, 0xe2, 0x70, 0x87, 0x69, 0xe0, 0x87, 0x69, 0xc0, 0xa1, 0xd6, 0x84, 0x8b, 0x1b, 0x62, 0x2f,
	0x0e, 0xe5, 0x42, 0x60, 0x01, 0x14, 0xa7, 0x29, 0x31, 0x24, 0xb1, 0x81, 0x83, 0xd1, 0x18, 0x10,
	0x00, 0x00, 0xff, 0xff, 0x9e, 0xd2, 0xad, 0x02, 0x53, 0x01, 0x00, 0x00,
}
